# Setup
title:               Calabria Weather Data
tagline:             'Wiki'
description:         'La Wiki ufficiale di <br><a href="#" target="_blank">Calabria Weather Data</a>'
url:                 http://cwd-wiki.tk
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             calabriaweatherdata@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: UA-146052-15
